---

- name: Configure DefaultKeyBindings.dict
  template:
    src: DefaultKeyBinding.dict
    dest: "{{ lookup('env', 'HOME') }}/Library/KeyBindings/DefaultKeyBinding.dict"
    mode: 0644

- name: Ensure Homebrew is installed
  block:

  - name: Check if homebrew installed
    stat:
      path: "{{ homebrew_install_dir }}"
    register: homebrew_exists_result

  - name: Make homebrew directory
    template:
      path: "{{ homebrew_install_dir }}"
      state: directory
    when: homebrew_exists_result.stat.exists == 'false' or homebrew_exists_result.stat.isdir == 'false'

  # Fuck /usr/local, fuck homebrew for defaulting to that
  - name: Install homebrew
    shell: >
      curl -L https://github.com/Homebrew/brew/tarball/master |
      tar xz --strip 1 -C "{{ homebrew_install_dir }}"
    when: homebrew_exists_result.stat.exists == 'false' or homebrew_exists_result.stat.isdir == 'false'

- name: Ensure homebrew packages are installed
  homebrew:
    path: "{{ homebrew_install_dir }}/bin"
    name: "{{ item }}"
  with_items:
  - autoconf
  - automake
  - bash-completion
  - coreutils
  - gnupg
  - go
  - govendor
  - nmap
  - openssl
  - p7zip
  - pandoc
  - par2
  - pwgen
  - python3
  - readline
  - the_platinum_searcher
  - tmux
  - unrar
  - wget
  - xz
