---
# assumes Debian 8 (jessie)
- hosts: blog-servers
  remote_user: root
  tasks:
  # Backports is required for Docker
  - name: Enable backports
    apt_repository: repo='deb http://http.debian.net/debian jessie-backports main' state=present update_cache=yes
  - name: Install docker
    apt: pkg=docker.io default_release=jessie-backports 
    notify: 
    - start-docker
  - name: Install pip
    easy_install: name=pip 
    #apt: pkg=python-pip
  - name: Install docker-py
    pip: name=docker-py version=1.1.0
  - name: Ghost container
    docker:
      name: younix-ghost
      image: ghost
      pull: always
      state: reloaded
      ports:
      - "127.0.0.1:2368:2368"
  - name: Install apache
    apt: name=apache2 update_cache=yes state=latest
  - name: Remove default apache configuration
    file: path=/etc/apache2/sites-enabled/000-default.conf state=absent
    notify: 
    - restart-apache
  - name: Add younix blog apache configuration
    copy: src=younix.us.conf dest=/etc/apache2/sites-available/younix.us.conf owner=root group=root mode=0644
    notify: 
    - restart-apache
  - name: Link younix blog apache configuration
    file: path=/etc/apache2/sites-enabled/younix.us.conf state=link src=../sites-available/younix.us.conf
    notify: 
    - restart-apache
  - name: Enable mod_rewrite
    apache2_module: name=rewrite state=present
    notify: 
    - restart-apache
  - name: Enable mod_proxy
    apache2_module: name=proxy state=present
    notify: 
    - restart-apache
  - name: Enable mod_proxy_http
    apache2_module: name=proxy_http state=present
    notify: 
    - restart-apache

  
  handlers: 
  - name: start-docker
    service: name=docker state=started
  - name: restart-apache
    service: name=apache2 state=restarted