# assumes Debian 8 (jessie)

---
# Install/configure Apache:
- hosts: blog-servers
  tasks:
  - name: Apache | Install apache
    apt: name=apache2 update_cache=yes state=latest
  - name: Remove default apache configuration
    file: path=/etc/apache2/sites-enabled/000-default.conf state=absent
    notify: 
    - restart-apache
  - name: Apache | Add younix blog configuration
    copy: src=apache.younix.us.conf dest=/etc/apache2/sites-available/younix.us.conf owner=root group=root mode=0644
    notify: 
    - restart-apache
  - name: Apache | Link younix blog configuration
    file: path=/etc/apache2/sites-enabled/younix.us.conf state=link src=../sites-available/younix.us.conf
    notify: 
    - restart-apache
  - name: Apache | Enable mod_rewrite
    apache2_module: name=rewrite state=present
    notify: 
    - restart-apache
  - name: Apache | Enable mod_proxy
    apache2_module: name=proxy state=present
    notify: 
    - restart-apache
  - name: Apache | Enable mod_proxy_http
    apache2_module: name=proxy_http state=present
    notify: 
    - restart-apache
  handlers: 
  - name: restart-apache
    service: name=apache2 state=restarted


# Install Docker
- hosts: blog-servers
  tasks:
  # Backports is required for Docker
  - name: Docker | Enable backports
    apt_repository: repo='deb http://http.debian.net/debian jessie-backports main' state=present update_cache=yes
  - name: Docker | Install docker
    apt: pkg=docker.io default_release=jessie-backports 
    notify: 
    - start-docker
  - name: Docker | Install pip
    easy_install: name=pip 
  - name: Docker | Install docker-py
    pip: name=docker-py version=1.1.0
  handlers: 
  - name: start-docker
    service: name=docker state=started


# Install Discourse
#- hosts: blog-servers
#  tasks: 