---
# assumes Debian 8 (jessie)
- hosts: blog-servers
  tasks:
  # Backports is required for Docker
  - name: Enable backports
    apt_repository: repo='deb http://http.debian.net/debian jessie-backports main' state=present update_cache=yes
  - name: Install docker
    apt: pkg=docker.io default_release=jessie-backports 
    notify: 
    - start-docker
  - name: Ghost container
    docker:
      name: younix-ghost
      image: ghost
      pull: always
      state: reloaded
      ports:
      - "127.0.0.1:2368:2368"
  - name: Install discourse
    docker: 
      name: younix-discourse
      image: discourse
      pull: always
      state: reloaded
      ports: 
  
  handlers: 
  - name: start-docker
    service: name=docker state=started