---

- name: TShock | Make config dir
  file: >
    path="{{ tshock_config_dir }}" 
    state=directory owner=marionettist1 group=marionettist1 mode=0700

# - name: TShock | Add server config file
#   copy: >
#     src=tshock.config.json 
#     dest="{{ tshock_config_dir }}/config.json" 
#     owner=root group=root mode=0644

- name: TShock | Pull Docker image
  docker:
    image: mrled/tshock:latest
    pull: always
    state: reloaded
    ports: 
    - "7777:7777/tcp"
    volumes:
    - "{{ tshock_config_dir }}:/terraria"
