"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Micah R Ledbetter"
email = "me@micahrl.com"

# To get my familiar git / delta style diffs, use:
#   [ui]
#   pager = "delta"
#   diff-formatter = ":git"
# delta has the very nice feature of language syntax highlighting in the terminal for diffs.

[colors]
# By default the :builtin pager uses underlines and green/red foreground colors
# to indicated added/removed text.
# I find this busy and hard to parse,
# so I change it to use background colors instead of underline.
"diff removed token" = { bg = "#221111", underline = false }
"diff added token" = { bg = "#002200", underline = false }
"diff token" = { reverse = true, underline = false }


[ui]
pager = ":builtin"

[ui.streampager]
# Use the alternate screen if the input is either long or takes more
# than 2 seconds to finish. Similar but not identical to `less -F -+X`.
interface = "quit-quickly-or-clear-output"

