"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Micah R Ledbetter"
email = "me@micahrl.com"

[colors]
# By default the :builtin pager uses underlines and green/red foreground colors
# to indicated added/removed text.
# I find this busy and hard to parse,
# so I change it to use background colors instead of underline.
"diff removed token" = { bg = "#221111", underline = false }
"diff added token" = { bg = "#002200", underline = false }
"diff token" = { reverse = true, underline = false }


[ui]
pager = ":builtin"

[ui.streampager]
# Use the alternate screen if the input is either long or takes more
# than 2 seconds to finish. Similar but not identical to `less -F -+X`.
interface = "quit-quickly-or-clear-output"

[template-aliases]
'format_field(key, value)' = 'label("log", key ++ ": ") ++ value'

# Adapted from the builtin_log_detailed template
# https://github.com/jj-vcs/jj/blob/main/cli/src/config/templates.toml#L255
# but with a line that shows added/removed lines of code
log_detailed_with_stats = 'log_detailed_with_stats(self)'
'log_detailed_with_stats(commit)' = '''
concat(
  "Commit ID: " ++ commit.commit_id() ++ "\n",
  "Change ID: " ++ commit.change_id() ++ "\n",
  surround("Bookmarks: ", "\n", separate(" ", commit.local_bookmarks(), commit.remote_bookmarks())),
  surround("Tags     : ", "\n", commit.tags()),
  "Author   : " ++ format_detailed_signature(commit.author()) ++ "\n",
  "Committer: " ++ format_detailed_signature(commit.committer())  ++ "\n",
  if(config("ui.show-cryptographic-signatures").as_boolean(),
    "Signature: " ++ format_detailed_cryptographic_signature(commit.signature()) ++ "\n"),
  "Changes  : " ++
    if(commit.empty(), "empty",
      concat(
        commit.diff().files().len() ++ " file" ++ if(commit.diff().files().len() != 1, "s") ++ ", ",
        commit.diff().stat().total_added() ++ " insertion" ++ if(commit.diff().stat().total_added() != 1, "s") ++ "(+), ",
        commit.diff().stat().total_removed() ++ " deletion" ++ if(commit.diff().stat().total_removed() != 1, "s") ++ "(-)"
      )
    ) ++ "\n",
  "\n",
  indent("    ",
    if(commit.description(),
      commit.description().trim_end(),
      label(if(commit.empty(), "empty"), description_placeholder)) ++ "\n"),
  "\n",
)
'''

[aliases]
# Delta for diff and show
# Delta has the very nice feature of language syntax highlighting in the terminal for diffs.
ddiff = ["diff", "--config=ui.pager=delta", "--config=ui.diff-formatter=:git"]
dshow = ["show", "--config=ui.pager=delta", "--config=ui.diff-formatter=:git"]

# A 'git log' like experience
gitlog = ["log", "-r", "all()", "-T", "builtin_log_detailed"]

# Use the custom template with file statistics
statlog = ["log", "-r", "all()", "-T", "log_detailed_with_stats"]

pushmaster = ["util", "exec", "--", "sh", "-c", """
jj new && jj bookmark move master -t @- && jj git push
"""]
