"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Micah R Ledbetter"
email = "me@micahrl.com"

[colors]
# By default the :builtin pager uses underlines and green/red foreground colors
# to indicated added/removed text.
# I find this busy and hard to parse,
# so I change it to use background colors instead of underline.
"diff removed token" = { bg = "#221111", underline = false }
"diff added token" = { bg = "#002200", underline = false }
"diff token" = { reverse = true, underline = false }


[ui]
pager = ":builtin"

[ui.streampager]
# Use the alternate screen if the input is either long or takes more
# than 2 seconds to finish. Similar but not identical to `less -F -+X`.
interface = "quit-quickly-or-clear-output"

[template-aliases]
'format_field(key, value)' = 'label("log", key ++ ": ") ++ value'

'log_detailed_with_stats' = '''
if(root,
  format_root_commit(self),
  concat(
    if(current_working_copy, "@", if(immutable, "◆", if(conflict, "x", "○"))) ++
    if(!mine, " ~", ""),
    "\n" ++ format_field("Commit ID", commit_id),
    if(divergent,
      "\n" ++ label("divergent",
        format_field("Change ID", concat(change_id, " !divergence!")))
    , "\n" ++ format_field("Change ID", change_id)),
    if(bookmarks, "\n" ++ format_field("Bookmarks", bookmarks)),
    if(git_head, " " ++ label("git_head", "git_head()")),
    "\n" ++ format_field("Author", author),
    "\n" ++ format_field("Committer", committer),
    if(!empty,
      "\n" ++ format_field("Changes",
        concat(
          self.diff().files().len() ++ " file" ++ if(self.diff().files().len() != 1, "s") ++ ", " ++
          self.diff().stat().total_added() ++ " insertion" ++ if(self.diff().stat().total_added() != 1, "s") ++ "(+), " ++
          self.diff().stat().total_removed() ++ " deletion" ++ if(self.diff().stat().total_removed() != 1, "s") ++ "(-)"
        )
      )
    ),
    if(description, "\n\n" ++ indent("    ", description)),
    if(!description, "\n\n" ++ indent("    ", label("empty", "(no description set)")))
  )
)
'''

[aliases]
# Delta for diff and show
# Delta has the very nice feature of language syntax highlighting in the terminal for diffs.
ddiff = ["diff", "--config=ui.pager=delta", "--config=ui.diff-formatter=:git"]
dshow = ["show", "--config=ui.pager=delta", "--config=ui.diff-formatter=:git"]

# A 'git log' like experience
gitlog = ["log", "-r", "all()", "-T", "builtin_log_detailed"]

# Use the custom template with file statistics
statlog = ["log", "-r", "all()", "-T", "log_detailed_with_stats"]
