"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Micah R Ledbetter"
email = "me@micahrl.com"

[colors]
# By default the :builtin pager uses underlines and green/red foreground colors
# to indicated added/removed text.
# I find this busy and hard to parse,
# so I change it to use background colors instead of underline.
"diff removed token" = { bg = "#221111", underline = false }
"diff added token" = { bg = "#002200", underline = false }
"diff token" = { reverse = true, underline = false }


[ui]
pager = ":builtin"

[ui.streampager]
# Use the alternate screen if the input is either long or takes more
# than 2 seconds to finish. Similar but not identical to `less -F -+X`.
interface = "quit-quickly-or-clear-output"

[aliases]
# Delta for diff and show
# Delta has the very nice feature of language syntax highlighting in the terminal for diffs.
ddiff = ["diff", "--config=ui.pager=delta", "--config=ui.diff-formatter=:git"]
dshow = ["show", "--config=ui.pager=delta", "--config=ui.diff-formatter=:git"]

# A 'git log' like experience
gitlog = ["log", "-r", "all()", "-T", "builtin_log_detailed"]
