#!/bin/sh
set -eu

if [ "$#" -ne 1 ] || [ -z "$1" ]; then
    printf 'Usage: %s /path/to/mac-keybindings.conf\n' "$0" >&2
    exit 1
fi

output="$1"
# Capture separately so a Ghostty failure cannot be hidden by a pipeline.
keybindings=$(ghostty +list-keybinds --default --plain)
tmp=$(mktemp "${output}.XXXXXX")
trap 'rm -f -- "$tmp"' 0
trap 'exit 1' HUP INT TERM

{
    printf '%s\n' \
        '# macOS keybindings' \
        '#' \
        '# Generated by running this script on a Mac:' \
        '#    generate-mac-keybindings.sh /path/to/mac-keybindings.conf' \
        '#' \
        '# To use these on a given host, add the following to config.local in this directory:' \
        '#    config-file = mac-keybindings.conf' \
        ''

    # The default Escape binding consumes the key even when no search is active,
    # preventing Vim from returning to normal mode. Make it conditional so Escape
    # closes an active Ghostty search, but otherwise passes through to the terminal.
    printf '%s\n' "$keybindings" | awk '
        $0 == "keybind = escape=end_search" {
            print "keybind = performable:escape=end_search"
            next
        }
        { print }
    '
} > "$tmp"

chmod 644 "$tmp"
mv -- "$tmp" "$output"
