# -*- mode: ruby -*-
# vi: set ft=ruby :

require "date"
require "fileutils"

Vagrant.require_version ">= 1.6.2"

Vagrant.configure("2") do |config|
    #config.vm.define "gheis-" + DateTime.now.strftime("%Y-%m-%d-%H-%M-%S")
    config.vm.define "tgirl-2015-11-20"
    config.vm.box = "wintriallab-windows_81_x86"
    config.vm.communicator = "winrm"
    
    config.vm.hostname = "tgirl"

    # Admin user name and password
    config.winrm.username = "vagrant"
    config.winrm.password = "V@grant123"

    config.vm.guest = :windows
    config.windows.halt_timeout = 15

    config.vm.network :forwarded_port, guest: 3389, host: 33389, id: "rdp", auto_correct: true

    config.vm.provider :virtualbox do |v, override|
        #v.gui = true
        v.customize ["modifyvm", :id, "--memory", 2048]
        v.customize ["modifyvm", :id, "--cpus", 2]
        v.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
        v.customize ["modifyvm", :id, "--accelerate2dvideo", "on"]
        v.customize ["modifyvm", :id, "--vram", 128]
        v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
        v.customize ["modifyvm", :id, "--draganddrop", "bidirectional"]
    end

    begin
        Dir.mkdir('./synced')
        rescue SystemCallError
            $stderr.print "Synced directory already exists...\r\n"
    end
    
    FileUtils.cp "../../scripts/wintriallab-postinstall.psm1", "./synced/"
    FileUtils.cp "./tgirl-postinstall.ps1", "./synced/"
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.synced_folder "./synced", "/marionettist", create: true
    
    config.vm.provision "shell", inline: "C:/marionettist/tgirl-postinstall.ps1"
end
