# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ":espanso"
    replace: "Hi there!"

  - trigger: ":dtime"
    replace: "{{dtime}}"
    vars:
      - name: dtime
        type: date
        params:
          format: "%Y%d%m:%H%M%S"
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y%d%m"

  - trigger: ":rituals"
    replace: "ALL RITUALS RESTRICTED. ALL RITES RESERVED."

# Stop telling me every fucking time I focus on a password field
secure_input_notification: false
