---
- name: Docker | Install APT HTTPS transport
  apt: pkg=apt-transport-https
- name: Docker | Install Docker APT key
  apt_key: >
    keyserver=hkp://p80.pool.sks-keyservers.net:80
    id=58118E89F3A912897C070ADBF76221572C52609D
- name: Docker | Enable Docker repository
  apt_repository: >
    repo='deb https://apt.dockerproject.org/repo debian-jessie main'
    state=present
    update_cache=yes
- name: Docker | Install docker
  apt: pkg=docker-engine
  notify: 
  - start-docker
- name: Docker | Install pip
  easy_install: name=pip 
- name: Docker | Install docker-py
  pip: name=docker-py version=1.1.0
