---
# In Debian Jessie, backports is required for Docker
- name: Docker | Enable backports
  apt_repository: repo='deb http://http.debian.net/debian jessie-backports main' state=present update_cache=yes
- name: Docker | Install docker
  apt: pkg=docker.io default_release=jessie-backports 
  notify: 
  - start-docker
- name: Docker | Install pip
  easy_install: name=pip 
- name: Docker | Install docker-py
  pip: name=docker-py version=1.1.0
