# -*- mode: ruby -*-
# vi: set ft=ruby :

require "date"
require "fileutils"

Vagrant.require_version ">= 1.6.2"

Vagrant.configure("2") do |config|
    #config.vm.define "gheis-" + DateTime.now.strftime("%Y-%m-%d-%H-%M-%S")
    config.vm.define "gheis-" + DateTime.now.strftime("%Y-%m-%d")
    config.vm.box = "windows_10_x86_virtualbox.box"
    config.vm.communicator = "winrm"
    
    config.vm.hostname = "gheis"

    # Admin user name and password
    config.winrm.username = "vagrant"
    config.winrm.password = "V@grant123"

    config.vm.guest = :windows
    config.windows.halt_timeout = 15

    config.vm.network :forwarded_port, guest: 3389, host: 3389, id: "rdp", auto_correct: true

    config.vm.provider :virtualbox do |v, override|
        #v.gui = true
        v.customize ["modifyvm", :id, "--memory", 2048]
        v.customize ["modifyvm", :id, "--cpus", 2]
        v.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
        v.customize ["modifyvm", :id, "--accelerate2dvideo", "on"]
        v.customize ["modifyvm", :id, "--vram", 128]
        v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
        v.customize ["modifyvm", :id, "--draganddrop", "bidirectional"]
    end

    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.synced_folder "./synced", "/vagrant", create: true
    FileUtils.cp "../../scripts/vagrant-postinstall.psm1" "./synced"
    FileUtils.cp "../../scripts/wintriallab-postinstall.psm1" "./synced"
    FileUtils.cp "./bitchbox-postinstall.ps1" "./synced"
    
    config.vm.provision "shell", inline: "C:/marionettist/bitchbox-postinstall.ps1"
end
