---
- name: Install required packages
  apt: pkg={{ item }} update_cache=yes state=latest
  with_items:
  - ca-certificates
  - libsasl2-modules
  - postfix
  - postfix-pcre

- name: Upload main.cf
  template: src=main.cf.j2 dest=/etc/postfix/main.cf
  notify:
  - restart-postfix

- name: Ensure root alias to {{ mail_relay_root_recipient }}
  lineinfile: 
    dest: /etc/aliases 
    line: "root: {{ mail_relay_root_recipient }}"
    insertafter: EOF
  notify:
  - newaliases

- name: Start Postfix
  service: name=postfix state=started
