---
# Install Ghost
# The dox for this Docker container are bullshit. The comments here are helpful 
# <https://registry.hub.docker.com/u/library/ghost/>
  - name: Ghost | Make ghost_content_dir
    file: path="{{ ghost_content_dir }}" state=directory owner=root group=root mode=0755
  - name: Ghost | Upload config.js
    template: src=ghost.config.js.j2 dest={{ ghost_content_dir }}/config.js owner=root group=root mode=0644
  - name: Ghost | Run Docker container
    docker:
      name: "{{ ghost_container_name }}"
      image: ghost
      pull: always
      state: reloaded
      ports: 
      - "127.0.0.1:2368:2368"
      volumes:
      - "{{ ghost_content_dir }}:/var/lib/ghost"
      env: 
        #VIRTUAL_HOST: "{{ hostname }}"
        NODE_ENV: production
  - name: Ghost | Test that container is up
    command: bash -c "docker ps | grep -e '\W{{ ghost_container_name }}\W*$'"
  - name: Ghost | Test that the web service is responding locally
    command: curl localhost:2368
  - name: Ghost | Test that the web service is responding to its proper URL
    command: curl "{{ ghost_url }}"
