#!/bin/sh

set -e
set -u

# Set these variables to match your environment
MAILDIR_RELPATH=.maildir
SPAMASSASSIN_USER=debian-spamd
SPAM_RECEIVING_USER=mrled
SPAM_RECEIVING_FOLDERNAME=.SPAM
SPAM_PROCESSED_FOLDERNAME=SPAM.processed

# Nothing should need to be changed below this line



SPAM_RECEIVING_MAILDIR="$(eval echo ~$SPAM_RECEIVING_USER/$MAILDIR_RELPATH)"
SPAM_RECEIVING_FOLDER=${SPAM_RECEIVING_MAILDIR}/.SPAM
SPAM_PROCESSED_FOLDERNAME=SPAM.processed
SPAM_PROCESSED_FOLDER="$(eval echo $SPAM_RECEIVING_MAILDIR/.$SPAM_PROCESSED_FOLDERNAME)"
TMP_SPAM_MAILDIR="$(eval echo ~${SPAMASSASSIN_USER}/tmp-spam-maildir)"

if [ ! -d $SPAM_RECEIVING_FOLDER ]; then
    echo "No such directory: $SPAM_RECEIVING_FOLDER. Nothing to do."
    exit 0
fi

if [ ! -d $TMP_SPAM_MAILDIR ]; then
    # It won't hurt if this already exists
    maildirmake $TMP_SPAM_MAILDIR
fi

if [ ! -d $SPAM_PROCESSED_FOLDER ]; then
    echo "Warning: Processed spam directory does not exist. Creating ${SPAM_PROCESSED_FOLDER}..."
    su $SPAM_RECEIVING_USER -l -c "maildirmake -f $SPAM_PROCESSED_FOLDERNAME $MAILDIR_RELPATH"
fi

if [ "$(ls -A $SPAM_RECEIVING_FOLDER/cur)" ]; then
    cp -r $SPAM_RECEIVING_FOLDER/cur/* $TMP_SPAM_MAILDIR/cur/
    chown -R $SPAMASSASSIN_USER $TMP_SPAM_MAILDIR

    mv $SPAM_RECEIVING_FOLDER/cur/* $SPAM_PROCESSED_FOLDER/cur/

    su $SPAMASSASSIN_USER -l -c "sa-learn --spam $TMP_SPAM_MAILDIR"
fi

rm -rf $TMP_SPAM_MAILDIR
