---

# TODO: better way to trigger the Docker build & upload? Right now if the upload fails, it cannot detect that the next time
# TODO: seems like the openvpn server process isn't noticing when its config changes. Fixme

- name: OpenVPN | Make openvpn_config_dir
  file: >
    path="{{ openvpn_config_dir }}" 
    state=directory owner=root group=root mode=0755

- name: OpenVPN | Add server config file
  template: >
    src=server.ovpn.j2 
    dest="{{ openvpn_config_dir }}/server.ovpn" 
    owner=root group=root mode=0644

- name: run openvpn docker
  docker:
    name: "{{ openvpn_container_name }}"
    image: "localhost:5000/{{ openvpn_image_name }}"
    pull: always
    state: reloaded
    cap_add: NET_ADMIN
    privileged: yes          # required because we deal with iptables and NAT in this container
    insecure_registry: yes   # who cares, this is all on localhost
    ports: 
    - "1194:1194/udp"
    - "1194:1194/tcp"
    volumes:
    - "{{ openvpn_config_dir }}:/etc/openvpn"


