---

# TODO: https://openvpn.net/index.php/open-source/documentation/howto.html#mitm

- name: Install OpenVPN
  apt: pkg=openvpn update_cache=yes state=latest
- name: Install sudo
  apt: pkg=sudo update_cache=yes state=latest

- name: Enable IPv4 forwarding
  sysctl: name="net.ipv4.ip_forward" value=1 state=present sysctl_set=yes reload=yes

- name: Add OpenVPN group
  group: name={{ openvpn_group }} system=yes state=present
  notify:
  - restart-openvpn
- name: Add OpenVPN user
  user: name={{ openvpn_user }} group={{ openvpn_group }} home=/etc/openvpn createhome=false shell=/usr/sbin/nologin system=yes state=present
  notify:
  - restart-openvpn

- name: Make /dev/net
  file: path=/dev/net state=directory owner=root group=root mode=0755
  notify:
  - restart-openvpn
- name: Make /dev/net/tun
  command: mknod /dev/net/tun c 10 200
  args: 
    creates: /dev/net/tun
  notify:
  - restart-openvpn

# This must happen before firewall rules can be applied
# This results in a new interface (viewable with 'ifconfig {{ openvpn_tun_devname }}')
# These do NOT survive a reboot
- name: Make OpenVPN tunnel device
  command: openvpn --mktun --dev {{ openvpn_tun_devname }} --dev-type tun --user {{ openvpn_user }} --group {{ openvpn_group }}
  args:
    creates: /sys/class/net/{{ openvpn_tun_devname }}
  notify:
  - restart-openvpn

- name: Allow OpenVPN user to "sudo /sbin/ip"
  template: src=openvpn.sudoers.j2 dest=/etc/sudoers.d/openvpn validate='visudo -cf %s'
  notify:
  - restart-openvpn

- name: Upload firewall configuration
  template: src=openvpn.ferm.j2 dest=/etc/ferm/ferm.conf.d/openvpn.ferm owner=root group=root mode=0644
  notify: 
  - apply-firewall

- name: Create configuration directory
  file: path=/etc/openvpn state=directory owner={{ openvpn_user }} group={{ openvpn_group }} mode=0755

- name: Upload sudo-ip script
  copy: src=sudo-ip.sh dest=/etc/openvpn/sudo-ip.sh owner={{ openvpn_user }} group={{ openvpn_group }} mode=0755
  notify:
  - restart-openvpn

- name: Upload server configuration
  template: src=server.ovpn.j2 dest=/etc/openvpn/openvpn.conf owner={{ openvpn_user }} group={{ openvpn_group }} mode=0600
  notify:
  - restart-openvpn
- name: Upload client configuration template
  template: src=client.ovpn.template.j2 dest=/etc/openvpn/client.ovpn.template owner={{ openvpn_user }} group={{ openvpn_group }} mode=0644
