---

- name: Install OpenVPN
  apt: pkg=openvpn update_cache=yes state=latest
- name: Install sudo
  apt: pkg=sudo update_cache=yes state=latest

- name: Enable IPv4 forwarding
  sysctl: name="net.ipv4.ip_forward" value=1 state=present sysctl_set=yes reload=yes

- name: Add OpenVPN group
  group: name={{ openvpn_group }} system=yes state=present
- name: Add OpenVPN user
  user: name={{ openvpn_user }} group={{ openvpn_group }} home=/etc/openvpn createhome=false shell=/usr/sbin/nologin system=yes state=present

- name: Make /dev/net
  file: path=/dev/net state=directory owner=root group=root mode=0755
- name: Make /dev/net/tun
  command: mknod /dev/net/tun c 10 200
  args: 
    creates: /dev/net/tun

# This must happen before firewall rules can be applied
# This results in a new interface (viewable with 'ifconfig {{ openvpn_tun_devname }}')
# These do NOT survive a reboot
- name: Make OpenVPN tunnel device
  command: openvpn --mktun --dev {{ openvpn_tun_devname }} --dev-type tun --user {{ openvpn_user }} --group {{ openvpn_group }}
  args:
    creates: /sys/class/net/{{ openvpn_tun_devname }}

- name: Allow OpenVPN user to "sudo /sbin/ip"
  template: src=openvpn.sudoers.j2 dest=/etc/sudoers.d/openvpn validate='visudo -cf %s'

# - name: Configure OpenVPN interface
#   template: src=openvpn.interface.j2 dest=/etc/network/interfaces.d/openvpn owner=root group=root mode=0644
- name: Configure iptables firewall
  template: src=openvpn.iptables.sh.j2 dest=/etc/network/if-pre-up.d/openvpn.iptables.sh owner=root group=root mode=0755

- name: Create configuration directory
  file: path=/etc/openvpn state=directory owner={{ openvpn_user }} group={{ openvpn_group }} mode=0755

- name: Upload sudo-ip script
  copy: src=sudo-ip.sh dest=/etc/openvpn/sudo-ip.sh owner={{ openvpn_user }} group={{ openvpn_group }} mode=0755

- name: Upload server configuration
  template: src=server.ovpn.j2 dest=/etc/openvpn/server.ovpn owner={{ openvpn_user }} group={{ openvpn_group }} mode=0644
  notify:
    - restart-openvpn
