[computer_Naragua]
aliases=@Invalid()
halfDuplexCapsLock=false
halfDuplexNumLock=false
halfDuplexScrollLock=false
modifierAlt=alt
modifierAltGr=altgr
modifierCtrl=ctrl
modifierMeta=meta
modifierShift=shift
modifierSuper=super
name=Naragua
switchCornerBottomLeft=false
switchCornerBottomRight=false
switchCornerSize=0
switchCornerTopLeft=false
switchCornerTopRight=false
xtestIsXineramaUnaware=false

[computer_Selganac]
name=Selganac

[computer_haluth]
name=haluth

[computer_orocroix]
name=orocroix

[core]
computerName=Naragua
coreMode=2
lastVersion=1.27.0.0

[gui]
closeReminder=false
enableUpdateCheck=true
logExpanded=true
shownFirstConnectedMessage=true
shownServerFirstStartMessage=true
startCoreWithGui=true

[internalConfig]
hotkeys\size=0
screens\1\name=
screens\10\name=
screens\11\name=
screens\12\name=
screens\13\name=
screens\14\name=
screens\15\name=
screens\2\name=
screens\3\name=
screens\4\name=
screens\5\name=
screens\6\name=
screens\7\name=
screens\8\name=Naragua
screens\9\name=
screens\size=15

[log]
level=Info

[server]
clipboardSize=3
defaultLockToComputerState=false
disableLockToComputer=false
enableClipboard=true
enableHeartbeat=false
enableSwitchDelay=false
enableSwitchDoubleTap=false
externalConfig=true
externalConfigFile=/Users/mrled/.dhd/opt/synergy/Server.conf
heartbeat=5000
protocol=barrier
relativeMouseMoves=false
switchDelay=250
switchDoubleTap=250
win32KeepForeground=false
