section: options
	keystroke(Control+Shift+F1) = switchToScreen(Naragua)
	keystroke(Control+Shift+F2) = switchToScreen(Selganac)
	keystroke(Control+Shift+F3) = switchToScreen(orocroix)
	keystroke(Control+Shift+F4) = switchToScreen(haluth)
end
