# TMUX configuration

set-option -g prefix C-t
source-file ~/.dhd/hbase/.tmux.base.conf

# C-t C-t moves to previously-selected window (as in screen)
bind-key C-t last-window

# Easily reload config
bind-key r source-file ~/.tmux.conf \; display-message "Config reloaded..."
