  vars:
    ghost_hostname: blog-dev.younix.us
    ghost_url: "http://{{ ghost_hostname }}/"
    ghost_container_name: younix-ghost
    ghost_content_dir: /srv/docker/ghostcontent

    discourse_hostname: 'talk-dev.younix.us'
    discourse_container_name: younix-discourse
    discourse_dir: '/srv/docker/discourse'

    swap_file_path: '/swapfile'
    swap_file_size_mb: 2048

  vars_files: 
    - secret.yml



  tasks:
  - name: Apache | Install apache
    apt: name=apache2 update_cache=yes state=latest

  - name: Apache | Remove default apache configuration
    file: path=/etc/apache2/sites-enabled/000-default.conf state=absent
    notify: 
    - restart-apache

  - name: Apache | Add generic configuration
    copy: src=apache.generic.conf dest=/etc/apache2/sites-available/generic.conf owner=root group=root mode=0644
    notify: 
    - restart-apache
  - name: Apache | Link generic configuration
    file: path=/etc/apache2/sites-enabled/generic.conf state=link src=../sites-available/generic.conf
    notify: 
    - restart-apache


  - name: Apache | Add younix blog configuration
    template: src=apache.ghost.conf.j2 dest=/etc/apache2/sites-available/ghost.conf owner=root group=root mode=0644
    notify: 
    - restart-apache
  - name: Apache | Link younix blog configuration
    file: path=/etc/apache2/sites-enabled/ghost.conf state=link src=../sites-available/ghost.conf
    notify: 
    - restart-apache
  - name: Apache | Add discourse configuration
    template: src=apache.discourse.conf.j2 dest=/etc/apache2/sites-available/discourse.conf owner=root group=root mode=0644
    notify: 
    - restart-apache
  - name: Apache | Link discourse configuration
    file: path=/etc/apache2/sites-enabled/discourse.conf state=link src=../sites-available/discourse.conf
    notify: 
    - restart-apache




  - name: Apache | Enable mod_rewrite
    apache2_module: name=rewrite state=present
    notify: 
    - restart-apache
  - name: Apache | Enable mod_proxy
    apache2_module: name=proxy state=present
    notify: 
    - restart-apache
  - name: Apache | Enable mod_proxy_http
    apache2_module: name=proxy_http state=present
    notify: 
    - restart-apache

