# -*- mode: ruby -*-
# vi: set ft=ruby :

require "date"

Vagrant.require_version ">= 1.6.2"

# Resolve paths before passing them to config.vm.provision
# I do this because, when run from my buildlab.ps1 script, I set ENV:VAGRANT_CWD to this directory, 
# but pushd away into a working directory on a bigger disk for actually keeping the VM
thisVagrantfileDir = File.dirname(__FILE__)
commonScriptsDir = "#{thisVagrantfileDir}/../../scripts"

Vagrant.configure("2") do |config|
    config.vm.define "isoupdater-windows_81_x86"
    config.vm.box = "wintriallab-windows_81_x86_noupdates"
    config.vm.communicator = "winrm"

    # Admin user name and password
    config.winrm.username = "vagrant"
    config.winrm.password = "V@grant123"

    config.vm.guest = :windows
    config.windows.halt_timeout = 15

    #config.vm.network :forwarded_port, guest: 3389, host: 3389, id: "rdp", auto_correct: true

    config.vm.provider :virtualbox do |v, override|
        #v.gui = true
        v.customize ["modifyvm", :id, "--memory", 1024]
        v.customize ["modifyvm", :id, "--cpus", 1]
        v.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
        v.customize ["modifyvm", :id, "--accelerate2dvideo", "on"]
        v.customize ["modifyvm", :id, "--vram", 128]
        v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
        v.customize ["modifyvm", :id, "--draganddrop", "bidirectional"]
    end

    config.vm.provision "file", source: "#{commonScriptsDir}/wintriallab-postinstall.psm1", destination: "marionettist/wintriallab-postinstall.psm1"
    config.vm.provision "file", source: "#{commonScriptsDir}/trial-iso-updater.ps1", destination: "marionettist/trial-iso-updater.ps1"
    config.vm.provision "file", source: "#{commonScriptsDir}/win-updates.ps1", destination: "marionettist/win-updates.ps1"
    config.vm.provision "file", source: "isoupdater-postinstall.ps1", destination: "marionettist/isoupdater-postinstall.ps1"

    config.vm.provision "shell", inline: 'powershell.exe -File "${ENV:UserProfile}/marionettist/isoupdater-postinstall.ps1"'
end
