[ovpnserver]
noradia.younix.us

[bitchboxen]
noradia.younix.us

[webappserver]
noradia.younix.us

[all:vars]

ansible_user = root

openvpn_server_name = vpn.younix.us
openvpn_private_network = 192.168.252.1/24

webapp_hostname = toys.younix.us
webapp_landing_desc = my web host for random shit I made

autobackup_enabled = true
autobackup_recipient_key_name = Micah R Ledbetter (Automatic Backup Encryption) <micah@micahrl.com>
autobackup_s3_bucket = backups-autobackup-89d9f33ec6b04b22b358c1fca9844264c063ae6b
autobackup_iam_access_key_id = {{ vault_autobackup_iam_access_key_id }}
autobackup_iam_secret_access_key = {{ vault_autobackup_iam_secret_access_key }}
