[ovpnserver]
noradia.younix.us

[bitchboxen]
noradia.younix.us

#[tshockserver]
#nullyork.younix.us

[webappserver]
noradia.younix.us


[all:vars]

ansible_user = root

openvpn_image_name      = younix_openvpn
openvpn_image_build_dir = /srv/docker-younix-openvpn-image

openvpn_server_name     = vpn.younix.us

# A /24 network: 
openvpn_private_subnet  = 192.168.252.0

#should be the first addr in the /24: 
openvpn_private_addr    = 192.168.252.1

webapp_hostname = toys.younix.us
webapp_landing_desc = my web host for random shit I made

autobackup_enabled = true
autobackup_recipient_key_name = Micah R Ledbetter (Automatic Backup Encryption) <micah@micahrl.com>
autobackup_s3_bucket = backups-autobackup-89d9f33ec6b04b22b358c1fca9844264c063ae6b
autobackup_iam_access_key_id = {{ vault_autobackup_iam_access_key_id }}
autobackup_iam_secret_access_key = {{ vault_autobackup_iam_secret_access_key }}
